---
title: "Heteroplasmy validations with ddPCR"
author: "Arslan Zaidi"
date: "7/4/2019"
output: html_document
---

```{r}

library(ggplot2)
library(dplyr)
library(here)
library(data.table)

```


```{r}
#read in ddPCR results
ddpcr<-read.table(here("Data_files/denovo_ddPCR_results_10122018.txt"),
                  header=T,
                  sep="\t")

#calculate average heteroplasmy frequency
avg.ddpcr<-ddpcr%>%
  group_by(FID,individual,tissue,position)%>%
  summarize(ddpcr_f=mean(ddpcr_f),miseq_f=mean(miseq_f))

#calculate correlation b/w Miseq and ddPCR frequency
rcoef<-round(with(avg.ddpcr,cor(miseq_f,ddpcr_f,use="complete.obs")),2)

#calculate average deviation
avg.dev<-round(with(avg.ddpcr,mean(ddpcr_f-miseq_f,na.rm=T)),2)

cor.plt<-ggplot(avg.ddpcr,aes(miseq_f,ddpcr_f))+
  geom_point(size=0.6)+
  stat_smooth(method="lm")+
  geom_abline(intercept=0,slope=1,color="red")+
  theme_bw()+
  geom_segment(aes(x=miseq_f,xend=miseq_f,y=miseq_f,yend=ddpcr_f),alpha=0.6)+
  annotate(geom="text",x=0.01,y=0.075,label=paste("r = ",rcoef,sep=""),size=6)+
  annotate(geom="text",x=0.01,y=0.07,label=paste("Avg. ddPCR - Miseq = ",avg.dev,sep=""),size=6)+
  theme(axis.title=element_text(size=15),axis.text=element_text(size=12))+
  labs(x="Miseq - MAF",y="ddPCR - frequency")

# ggsave("Denovo_mutation_analysis/miseq_v_ddpcr_validations.pdf",cor.plt,height=7,width=7)

cor.plt

```


In all four cases, only the individual in whom the heteroplasmy was discovered was found to be heteroplasmic (MAF>1%) using ddPCR. No other individual in the family was heteroplasmic. The allele frequency from ddPCR, while highly correlated with Miseq allele frequency, is upwardly biased for some reaosn. 

